### PR TITLE
Update custom.css

### PR DESCRIPTION
**Pull request by jlaehne**
I really like changes to `css` done on https://www.aiida.net

The ones that I got to work here are:
- Slightly larger font in the top navigation bar [straightforward block in ``custom.css`]
- Less obvious external link symbols in the top navigation bar [straightforward block in ``custom.css`]
- Wider page only for the landing page, because otherwise sub-pages like 'about' look too wide
  [`extensions/selective_css.py`, which is loaded from `conf.py` and `_static/frontpage.css`]
- Set custom font [`@import` and `font` block in `customs.css`; preconnect in `_templates/layout.html` is optional and now removed]
- use same sized 'svg' logos in light/dark mode to avoid differences

(replaces #51)

### CODE REVIEW

**Comment by ericpre** [comment]
Is it normal that this PR is to be merged into https://github.com/hyperspy/hyperspy-website/tree/css?

> * Slightly larger font in the top navigation bar

It doesn't look larger to me but this may be due to the custom font.

> * Set custom font

It seems that this font is smaller than the default font and would need to be increased. Other than the different seems to be marginal, is it worth changing font? I would trend to stay with the default and avoid playing too much with the CSS.

**Comment by jlaehne** [comment]
Here is how it renders with Noto on my PC:
image

**Comment by ericpre** [comment]
Thank you for the explanation, Noto is not installed, that would explain the difference in font size. Yeah, I am convinced neither that it is worth the effort figuring out how to get a custom font to work on most system.

**Comment by jlaehne** [comment]
Looking for other projects that have a `pydata_sphinx_theme/layout.html` file according to https://pydata-sphinx-theme.readthedocs.io/en/v0.8.1/user_guide/customizing.html#replacing-removing-fonts it is actually quite easy to load a custom google font like Noto Sans.

Checked it on a computer that does not have Noto installed and looks good! Can you also check @ericpre?

**Comment by ericpre** [comment]
The font of the top navigation bar is larger but other than that, I can't see a difference between this branch (on the readthedocs preview) and the hyperspy.org version

**Comment by jlaehne** [comment]
OK, I was still missing a line in the css file. The weight of the bold font could still be adapted making it slightly lighter using 600 instead of 700.

For the record, adapted from https://github.com/AdaptiveMotorControlLab/CEBRA/blob/main/docs/source/_templates/layout.html and https://github.com/AdaptiveMotorControlLab/CEBRA/blob/main/docs/source/_static/css/custom.css

**Comment by jlaehne** [comment]
I realized, we actually used `Lato` in the logo and not `Noto Sans` (that was just used for the IO). Here is a comparison:

**Noto Sans:**
image

**Lato:**
image

**Comment by ericpre** [comment]
Do we know what is the font used in `pydata-sphinx-theme`? It looks very similar to Noto Sans (is it system dependent?). Maybe it would be more simple to have the hyperspy logo to use the same font as the `pydata-sphinx-theme`?

In the screenshot above, Lato is more difficult to read than Noto Sans.

**Comment by jlaehne** [comment]
The standard font order seems to be:
```
font-family: -apple-system, BlinkMacSystemFont, Segoe UI, "Helvetica Neue", Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol
```

I realize that also https://numpy.org is customizing the font and using `Lato` for titles and `Open Sans` or fallback fonts for the text. Actually an approach I do like as well - I am tempted to copy that.

**Comment by ericpre** [comment]
> I realize that also https://numpy.org/doc/stable documentation is customizing the font and using Lato for titles and Open Sans or fallback fonts for the text. 

Well, I can't tell! 😅 

In my opinion, the choice of the font should be defined based on an accessibility criteria and I would rely on the default from `pydata-sphinx-theme` as they have been working on the [accessibility of the theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/accessibility.html).

**Comment by jlaehne** [comment]
Well, for a documentation I totally agree with you. For a website, I find a little extra touch away from the absolute standard and a more homogeneous design (details on both fonts that are close to the logo than with the standard fonts, at least for section titles) make it more appealing. But surely that is personal preference.

**Comment by ericpre** [comment]
I am not against changing the fonts but my preference to rely on the default used in `pydata-sphinx-theme` is to avoid introducing maintenance burden. I have small concerns that some of these customisation are not fully working as expected (for example, in this PR, it needed some tweaks to work on various platform) or will break at some point - for example, some customisation in the previous version of the website were not compatible with recent sphinx (>=6?) and the website will build without failure but there was some issues (I don't remember what exactly).
This is why, I am questioning if this is worth it. Also we have limited expertise in these things and how do we know that the customisation are correct?

Maybe the way forward would be to get these customisation implemented in `pydata-sphinx-theme`? Maybe following up on https://github.com/pydata/pydata-sphinx-theme/issues/1060. We could try them here and submit the changes to `pydata-sphinx-theme` to get feedback on the changes, get them merged, etc.

**Comment by jlaehne** [comment]
I added some explanations to the initial post.

The font is a mere `.css` change (loading it directly from google-fonts with system fonts as fallback in case people should block the loading). I will leave out the `preconnect`, as the `numpy` documentation works without as well. So now, there should be no maintenance 'risk' in adapting the font and such a wide page on sub-pages does not look well.

The more elaborate change is the column width change only on the front page, where we could move to an upstreamed solution if that should become available in the future. However, I do not see why the scripted decision of loading two different css files should stop working.

Now also uses the same logos as svg in light/dark to be more consistent.

**Comment by ericpre** [comment]
> The more elaborate change is the column width change only on the front page, where we could move to an upstreamed solution if that should become available in the future. However, I do not see why the scripted decision of loading two different css files should stop working.

In line of https://github.com/pydata/pydata-sphinx-theme/issues/1060, I think that it would still be useful (for the community in general but also for the maintenance) to try to get as much as possible of these changes (page width for example) in pydata-sphinx-theme.
As we usually do in this type of situation, once the feature are integrated in pydata-sphinx-theme, we can start using it and clean up/simplify the customisation in this repository.

**Pull request merged**
