### PR TITLE
Change hyperspectral -> multi-dimensional in banner

### PR DESCRIPTION
**Pull request by francisco-dlp**
Change the website banner.

Current:

hyperspy_banner

Proposed:

hyperspy_banner

### CODE REVIEW

**Comment by to266** [comment]
I would slightly increase the gap between the hypercube and "m" in "multi" - looks quite cluttered at the moment

**Comment by francisco-dlp** [comment]
Is this better?

hyperspy_banner

**Comment by to266** [comment]
I think so, if the right side does not get cropped :)

**Comment by francisco-dlp** [comment]
I have updated the file in the PR so it should be fine now. However, let's wait until the release tomorrow to merge the changes to the website so that everybody can participate in the discussions.

**Comment by francisco-dlp** [comment]
This is the updated file:

hyperspy_banner

In [this link](https://dl.dropboxusercontent.com/u/479148/hyperspy_banner.svg) you can download the svg file in case that someone wants to perform further improvements.

**Comment by to266** [comment]
The svg looks to be cropped (the right side)... otherwise sure, let's wait for tomorrow

**Comment by francisco-dlp** [comment]
Sorry, I forgot to save the file before sharing. It should be fine now.

**Pull request merged**
